using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;

namespace Game
{
    class AbilitiesXML
    {
        public void Run()
        {
            XMLReadPrint("Fireball", 3);
        }

        /// <summary>
        /// This writes a new Abilities.xml with basic abilities.
        /// </summary>
        public void XMLWriteMethod()
        {
            XmlWriterSettings settings = new XmlWriterSettings();
            settings.Indent = true;

            XmlWriter writer = XmlWriter.Create("Abilities.xml", settings);
            writer.WriteStartDocument();
            writer.WriteComment("This file is generated by the program.");
            writer.WriteStartElement("Abilities");

            writer.WriteStartElement("Ability");
            writer.WriteAttributeString("ID", "1");
            writer.WriteAttributeString("Name", "Freeze");
            writer.WriteElementString("DamageEffect", "Ice");
            writer.WriteElementString("StatusEffect", "Freeze");
            writer.WriteStartElement("Stats");
            writer.WriteAttributeString("Level", "1");
            writer.WriteAttributeString("Cost", "100");
            writer.WriteAttributeString("Power", "6");
            writer.WriteEndElement();
            writer.WriteStartElement("Stats");
            writer.WriteAttributeString("Level", "2");
            writer.WriteAttributeString("Cost", "110");
            writer.WriteAttributeString("Power", "8");
            writer.WriteEndElement();
            writer.WriteStartElement("Stats");
            writer.WriteAttributeString("Level", "3");
            writer.WriteAttributeString("Cost", "120");
            writer.WriteAttributeString("Power", "10");
            writer.WriteEndElement();
            writer.WriteStartElement("Stats");
            writer.WriteAttributeString("Level", "4");
            writer.WriteAttributeString("Cost", "130");
            writer.WriteAttributeString("Power", "12");
            writer.WriteEndElement();
            writer.WriteStartElement("Stats");
            writer.WriteAttributeString("Level", "5");
            writer.WriteAttributeString("Cost", "140");
            writer.WriteAttributeString("Power", "14");
            writer.WriteEndElement();
            writer.WriteEndElement();

            writer.WriteStartElement("Ability");
            writer.WriteAttributeString("ID", "2");
            writer.WriteAttributeString("Name", "Fireball");
            writer.WriteElementString("DamageEffect", "Fire");
            writer.WriteElementString("StatusEffect", "Burn");
            writer.WriteStartElement("Stats");
            writer.WriteAttributeString("Level", "1");
            writer.WriteAttributeString("Cost", "100");
            writer.WriteAttributeString("Power", "6");
            writer.WriteEndElement();
            writer.WriteStartElement("Stats");
            writer.WriteAttributeString("Level", "2");
            writer.WriteAttributeString("Cost", "110");
            writer.WriteAttributeString("Power", "8");
            writer.WriteEndElement();
            writer.WriteStartElement("Stats");
            writer.WriteAttributeString("Level", "3");
            writer.WriteAttributeString("Cost", "120");
            writer.WriteAttributeString("Power", "10");
            writer.WriteEndElement();
            writer.WriteStartElement("Stats");
            writer.WriteAttributeString("Level", "4");
            writer.WriteAttributeString("Cost", "130");
            writer.WriteAttributeString("Power", "12");
            writer.WriteEndElement();
            writer.WriteStartElement("Stats");
            writer.WriteAttributeString("Level", "5");
            writer.WriteAttributeString("Cost", "140");
            writer.WriteAttributeString("Power", "14");
            writer.WriteEndElement();
            writer.WriteEndElement();

            writer.WriteEndDocument();

            writer.Flush();
            writer.Close();
        }

        public void XMLReadPrint(string abilityName, int abilityLevel)
        {
            XmlReader reader = XmlReader.Create("Abilities.xml");

            while (reader.Read())
            {
                if (reader.NodeType == XmlNodeType.Element && reader.Name == "Abilities")
                {
                    reader.Read();
                    while (reader.Depth >= 1)
                    {
                        reader.Read();
                        if (reader.NodeType == XmlNodeType.Element && reader.Name == "Ability" && reader.GetAttribute(1) == abilityName)
                        {
                            //Console.WriteLine("ID = " + reader.GetAttribute(0));
                            Console.WriteLine("Name   = " + reader.GetAttribute(1));

                            while (reader.NodeType != XmlNodeType.EndElement)
                            {
                                reader.Read();

                                if (reader.Name == "DamageEffect")
                                {
                                    while (reader.NodeType != XmlNodeType.EndElement)
                                    {
                                        reader.Read();
                                        if (reader.NodeType == XmlNodeType.Text)
                                        {
                                            Console.WriteLine("DamEff = " + reader.Value);
                                        }
                                    }
                                    reader.Read();
                                }

                                if (reader.Name == "StatusEffect")
                                {
                                    while (reader.NodeType != XmlNodeType.EndElement)
                                    {
                                        reader.Read();
                                        if (reader.NodeType == XmlNodeType.Text)
                                        {
                                            Console.WriteLine("StaEff = " + reader.Value);
                                        }
                                    }
                                    reader.Read();
                                }

                                if (reader.NodeType == XmlNodeType.Element && reader.Name == "Stats" && reader.GetAttribute(0) == abilityLevel.ToString())
                                {
                                    Console.WriteLine("Level  = " + reader.GetAttribute(0));
                                    Console.WriteLine("Cost   = " + reader.GetAttribute(1));
                                    Console.WriteLine("Power  = " + reader.GetAttribute(2));

                                    while (reader.NodeType != XmlNodeType.EndElement)
                                    {
                                        reader.Read();
                                    }
                                } //end if

                            }
                        }
                    }
                }
            }
        }

        public Ability XMLReadReturn(string abilityName, int abilityLevel)
        {
            XmlReader reader = XmlReader.Create("Abilities.xml");
            Ability ability = new Ability();

            while (reader.Read())
            {
                if (reader.NodeType == XmlNodeType.Element && reader.Name == "Abilities")
                {
                    reader.Read();
                    while (reader.Depth >= 1)
                    {
                        reader.Read();
                        if (reader.NodeType == XmlNodeType.Element && reader.Name == "Ability" && reader.GetAttribute(1) == abilityName)
                        {
                            //Console.WriteLine("Name   = " + reader.GetAttribute(1));
                            ability.Name = reader.GetAttribute(1);

                            while (reader.NodeType != XmlNodeType.EndElement)
                            {
                                reader.Read();

                                if (reader.Name == "DamageEffect")
                                {
                                    while (reader.NodeType != XmlNodeType.EndElement)
                                    {
                                        reader.Read();
                                        if (reader.NodeType == XmlNodeType.Text)
                                        {
                                            //Console.WriteLine("DamEff = " + reader.Value);
                                            ability.DamageEffect = reader.Value;
                                        }
                                    }
                                    reader.Read();
                                }

                                if (reader.Name == "StatusEffect")
                                {
                                    while (reader.NodeType != XmlNodeType.EndElement)
                                    {
                                        reader.Read();
                                        if (reader.NodeType == XmlNodeType.Text)
                                        {
                                            //Console.WriteLine("StaEff = " + reader.Value);
                                            ability.StatusEffect = reader.Value;
                                        }
                                    }
                                    reader.Read();
                                }

                                if (reader.NodeType == XmlNodeType.Element && reader.Name == "Stats" && reader.GetAttribute(0) == abilityLevel.ToString())
                                {
                                    //Console.WriteLine("Level  = " + reader.GetAttribute(0));
                                    //Console.WriteLine("Cost   = " + reader.GetAttribute(1));
                                    //Console.WriteLine("Power  = " + reader.GetAttribute(2));

                                    ability.Level = int.Parse(reader.GetAttribute(0));
                                    ability.Cost = int.Parse(reader.GetAttribute(1));
                                    ability.Power = int.Parse(reader.GetAttribute(2));

                                    while (reader.NodeType != XmlNodeType.EndElement)
                                    {
                                        reader.Read();
                                    }
                                } //end if

                            }
                        }
                    }
                }
            }

            return ability;
        }

    }
}